version: "3.3"
services:
  api:
    build:
      context: ../api
      dockerfile: ../docker/api.prod.Dockerfile
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../api:/usr/src/api
    expose:
      - 1337
    ports:
      - 1337:1337
    env_file: ../.env
    environment:
      WAIT_HOSTS: db:27017,redis:6379
      WAIT_HOSTS_TIMEOUT: 120

  client:
    stdin_open: true
    build:
      context: ../client
      dockerfile: ../docker/client.prod.Dockerfile
    restart: unless-stopped
    networks:
      - network
    volumes:
      - ../client:/usr/src/client
    ports:
      - 3000:3000
    env_file: ../.env
   
  db:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - network

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    driver: bridge

